baseURL: https://evanslack.dev/
languageCode: en-us
title: evanslack.dev
theme: "PaperMod"

params:
  defaultTheme: dark
  disableThemeToggle: false
  hideSummary: false
  hideFooter: false
  keywords: [test,test2]

  homeInfoParams:
    Title: Hi, I'm Evan
    Content: >
        I'm a design engineer focused on building products and applications.


        &nbsp;


        From responsive web apps and distributed real-time messaging all the way down to embedded firmware and PCB design,
        I leverage my experience across many domains to deliever efficient solutions.

  socialIcons: 
    - name: "Github"
      url: "https://github.com/evanofslack"
    - name: "Linkedin"
      url: "https://www.linkedin.com/in/evanslack/"

menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 5
    - identifier: about
      name: about
      url: /about/
      weight: 10
    - identifier: projects
      name: projects
      url: /projects/
      weight: 15